### ISSUE TITLE
Difficulty Scaling

### ISSUE THREAD

**Issue by thor12022** [thor12022/HardcoreWither#4]
Difficulty of the Wither should scale depending on several factors:
- [x] Player Wither Experience, Issue #2 
- [ ] World Wither Experience, Issue #3 
- [ ] ?

Should affect the Wither by:
- [x] Scaling Minion Spawning, Issue #1 
- [x] Scaling Wither's Health
- [ ] Scaling Wither's Damage
- [ ] Scaling Wither's Defense
- [ ] ?

The basic Wither, with no scaling should be a Vanilla Wither.

Further thoughts, to vary it up a bit scaling should be done on a randomized point-buy system. The Wither gets a pool of points based upon aforementioned scaling to select random upgrades from.

For example, there are three players in the vicinity of the Wither spawn with 3, 1, 7 Wither Experience apiece. This gives the Wither 11 points worth of upgrades, it randomly selects: 30% Health boost (1pt/10%), Strength I (3pts), & Minion Spawning I (5pts).

Note: if no player is within range when Wither spawns they pool size should be 1 greater than the last Wither that was spawned.
